<?php
/**
 * Copyright (c) 2008-2010 dotSource GmbH.
 * All rights reserved.
 * http://www.dotsource.de
 *
 * Created:
 * 17.05.2010 15:05:16
 *
 * Contributors:
 * dcarl - initial contents
 */

/* @var $this Dotsource_Paymentoperator_Block_Checkout_Paypal_Shortcut */
?>
<li>
    <a href="<?php echo $this->getCheckoutUrl()?>" title="<?php echo Mage::helper('paypal')->__('PayPal Checkout');?>">
        <img src="<?php echo $this->getImageUrl()?>" alt="<?php echo Mage::helper('paypal')->__('PayPal Checkout');?>" />
    </a>
</li>