

<!--<form action="--><?php //echo $this->getUrl('*/*/generateCategoryRelations') ?><!--" method="post">-->
<!--    <input name="form_key" type="hidden" value="--><?php //echo $this->getFormKey() ?><!--" />-->
<!--    <button class="scalable" type="submit"><span>Generate category relations</span></button>-->
<!--</form>-->


<form action="<?php echo $this->getUrl('*/*/importAttributes') ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
    <button class="scalable" type="submit"><span>Import attributes</span></button>
</form>