<?php
/**
 * Copyright (c) 2008-2011 dotSource GmbH.
 * All rights reserved.
 * http://www.dotsource.de
 *
 * Contributors:
 * Erik Wohllebe - initial contents
 */
?>
<?php
/* @var $this Dotsource_Paymentoperator_Block_Form_Billpay_Eft */
$_code          = $this->getMethodCode();
$eftOwnerKey    = Dotsource_Paymentoperator_Model_Payment_Billpay_Abstract::KEY_EFT_OWNER;
$eftBanKey      = Dotsource_Paymentoperator_Model_Payment_Billpay_Abstract::KEY_EFT_BAN_ENC;
$eftBcnKey      = Dotsource_Paymentoperator_Model_Payment_Billpay_Abstract::KEY_EFT_BCN;
?>
    <li id="<?php echo $this->getContainerName($eftOwnerKey); ?>">
        <label for="<?php echo $this->getFieldName($eftOwnerKey); ?>" class="required"><em>*</em><?php echo $this->__('Account holder') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $this->getFieldName($eftOwnerKey); ?>" name="payment[<?php echo $this->getFieldName($eftOwnerKey); ?>]" title="<?php echo $this->__('Account holder') ?>" class="input-text required-entry validate-length maximum-length-50" value="<?php echo $this->escapeHtml($this->getBillpayEftOwner()) ?>" maxlength="50" />
        </div>
    </li>
    <li id="<?php echo $this->getContainerName($eftBanKey); ?>">
        <label for="<?php echo $this->getFieldName($eftBanKey); ?>" class="required"><em>*</em><?php echo $this->__('Bank account number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $this->getFieldName($eftBanKey); ?>" name="payment[<?php echo $this->getFieldName($eftBanKey); ?>]" title="<?php echo $this->__('Bank account number') ?>" class="input-text required-entry validate-number validate-length maximum-length-10" value="<?php echo $this->escapeHtml($this->getBillpayEftBan()) ?>" maxlength="10" />
        </div>
    </li>
    <li id="<?php echo $this->getContainerName($eftBcnKey); ?>">
        <label for="<?php echo $this->getFieldName($eftBcnKey); ?>" class="required"><em>*</em><?php echo $this->__('Bank code number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $this->getFieldName($eftBcnKey); ?>" name="payment[<?php echo $this->getFieldName($eftBcnKey); ?>]" title="<?php echo $this->__('Bank code number') ?>" class="input-text required-entry validate-number validate-length maximum-length-8" value="<?php echo $this->escapeHtml($this->getBillpayEftBcn()) ?>" maxlength="8" />
        </div>
    </li>