<?php
/**
 * Copyright (c) 2008-2011 dotSource GmbH.
 * All rights reserved.
 * http://www.dotsource.de
 *
 * Created:
 * 13.01.2011 09:04:42
 *
 * Contributors:
 * mdaehnert - initial contents
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li><?php echo $this->__('At the end of the checkout process you will be redirected to the payment site.'); ?></li>
</ul>
