<?php
/**
 * Copyright (c) 2008-2010 dotSource GmbH.
 * All rights reserved.
 * http://www.dotsource.de
 *
 * Created:
 * 27.04.2010 14:25:17
 *
 * Contributors:
 * dcarl - initial contents
 */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li><?php echo $this->__('At the end of the checkout process you will be redirected to the payment site.'); ?></li>
</ul>