<?php
/**
 * Copyright (c) 2008-2011 dotSource GmbH.
 * All rights reserved.
 * http://www.dotsource.de
 *
 * Created:
 * 11.01.2011 10:30:25
 *
 * Contributors:
 * mdaehnert - initial contents
 */
?>
<?php if ($this->getAdditionalText()): ?>
<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->getAdditionalText(); ?>
        </li>
    </ul>
</fieldset>
<?php endif; ?>