<?php
/**
 * Copyright (c) 2008-2011 dotSource GmbH.
 * All rights reserved.
 * http://www.dotsource.de
 *
 * Contributors:
 * Erik Wohllebe - initial contents
 */

/* @var $this Mage_Checkout_Block_Agreements */
?>
<?php if (!$this->getAgreements()) return; ?>
<script type="text/javascript">
//<![CDATA[
    //Create a agreement sync instance if need
    if (typeof AgreementSync == 'undefined') {
        AgreementSync = new DotsourceAgreementSync("ds-sync-agreement", "ds-sync-agreement-group");
    }

    //Hide the container
    AgreementSync.hideElement("payment-buttons-container");

    //Create a risk instance if need
    if (typeof RiskStep == 'undefined') {
    	RiskStep = new DotsourceRisk(
            "co-payment-form",
            "agreement-payment",
            "<?php echo Mage::getUrl('paymentoperator/checkout/risk') ?>",
            AgreementSync.showElement.bind(AgreementSync, "payment-buttons-container")
        );
    }
//]]>
</script>
<dl class="sp-methods" id="checkout-payment-method-load">
    <ol class="checkout-agreements ds-sync-agreement-group" style="border:none; padding:0;"> <!-- Rest these styles -->
    <?php foreach ($this->getAgreements() as $_a): ?>
        <li>
            <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
            <?php if ($_a->getIsHtml()): ?>
                <?php echo $_a->getContent() ?>
            <?php else:?>
                <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
            <?php endif; ?>
            </div>
            <p class="agree">
                <input type="checkbox" id="payment-agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox required-entry ds-sync-agreement ds-sync-agreement-<?php echo $_a->getId()?>" /><label for="payment-agreement-<?php echo $_a->getId()?>"><?php echo $this->htmlEscape($_a->getCheckboxText()) ?></label>
            </p>
        </li>
    <?php endforeach; ?>
    </ol>
</dl>
<div class="buttons-set" id="agreement-payment-buttons-container">
    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button id="agreement-payment-button" onclick="RiskStep.save()" type="button" class="button"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span class="please-wait" id="agreement-payment-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>